name: scrabble_examples

environment:
    sdk: ">=2.12.0 <3.0.0"

dependencies:
    scrabble: any

dependency_overrides:
    scrabble:
        path: ..

dev_dependencies:
    build_runner: ^1.10.11
    build_web_compilers: ^2.16.0
