name: scrabble_examples

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  scrabble:
    path: ..    # TODO Remove after publish scrabble package

dev_dependencies:
  build_runner: ^1.10.11
  build_web_compilers: ^2.16.0
