builders:

  compressBuilder:
    import: "package:scrabble/builder.dart"
    builder_factories: ["compressBuilder"]
    build_extensions: {".txt": [".dart"]}
    build_to: source
    auto_apply: root_package